export const FETCHING_PEOPLE = "FETCHING_PEOPLE";
export const FETCHING_PEOPLE_SUCCESS = "FETCHING_PEOPLE_SUCCESS";
export const FETCHING_PEOPLE_FAILURE = "FETCHING_PEOPLE_FAILURE";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
